### ISSUE TITLE
Улучшить экшен\валидацию со spec.yml

### ISSUE THREAD

**Issue by fey** [hexlet-basics/exercises-action#1]
В чем суть - в Kotlin переименовали файлики с тестами - Test.kt -> Test.java
В spec.yml это забыли сделать.
Пайплайн прошел, но сборка версии курсов на бейзиксе не проходит

```
Error class: Errno::ENOENT message: No such file or directory @ rb_sysopen - /var/tmp/hexletbasics/exercises-kotlin/modules/10-basics/10-hello-world/Test.kt
```

Можно сразу проверять наличие указанных spec файликов в модулях

**Comment by corsicanec82** [comment]
А это нам нужно тут?

Задача экшена только запустить нужную команду в репе. А вот эта команда уже и должна падать в таких случаях. В данном случае был косяк в репе котлина при запуске тестов, потому как там всегда возвращался код 0.
С таким успехом мы можем провалидировать spec, но всё равно тесты могут не проходить и возвращать код 0.

Также по валидации spec. Думаю её место в базовом образе exercises-base, а не в экшене. Все валидации у нас там. И команду добавить в common.mk.

**Comment by fey** [comment]
Да, можно и так.

**Comment by corsicanec82** [comment]
Плюс, если добавим логику в экшн, то это никак не поможет увидеть ошибку локально.
Экшн дёргает make check, а туда зашивай всё что нужно, плюс локально это будет работать.
